"""Step 1 — Organise source files into the output folder structure.

Source layout (cascade/AB01_Jinwoo/):
  ab01_jinwoo_awinda/             Vicon no-exo session
  ab01_jinwoo_hip_exo/            Vicon hip-exo session
  ab01_jinwoo_knee_exo/           Vicon knee-exo session
  *_no_exo.osim                   No-exo scaled model
  *_hip_exo_added_inertia.osim    Hip-exo scaled model (with added inertia)
  *_knee_exo_added_inertia.osim   Knee-exo scaled model (with added inertia)
  *_scale_set.xml                 Scale-set XML files

Output layout (data/AB01_Jinwoo/):
  opensim/                        All .osim and scale-set .xml files
  awinda/
    marker/   .trc marker trajectories
    grf/      .mot force-plate data
    mocap/    .csv Vicon CSV exports
    ik/       pre-existing *_ik.mot (will be overwritten by run_ik.py)
    id/       (created empty; populated by run_id.py)
  hip-exo/    (same sub-structure)
  knee-exo/   (same sub-structure)

Usage (from project root):
    python code/organise.py
    python code/organise.py --subject-root cascade/AB01_Jinwoo --output-dir data/AB01_Jinwoo
    python code/organise.py --dry-run
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from utils import (
    FOLDER_TYPE_TO_OUTPUT,
    OUTPUT_SUBFOLDERS,
    SKIP_EXTENSIONS,
    discover_trial_dirs,
    extract_trial_name,
)

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = PROJECT_ROOT / "cascade" / "AB01_Jinwoo"
DEFAULT_OUTPUT = PROJECT_ROOT / "data" / "AB01_Jinwoo"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _copy(src: Path, dst: Path, dry_run: bool) -> None:
    rel_dst = dst.relative_to(PROJECT_ROOT) if PROJECT_ROOT in dst.parents else dst
    if dry_run:
        print(f"  [dry]  {src.name:<52}  →  {rel_dst}")
    else:
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        print(f"  copied {src.name:<52}  →  {rel_dst}")


# ---------------------------------------------------------------------------
# OpenSim model files
# ---------------------------------------------------------------------------

def organise_opensim(subject_root: Path, output_dir: Path, dry_run: bool) -> None:
    """Copy all .osim and *scale_set*.xml files to output/opensim/."""
    opensim_dir = output_dir / "opensim"
    count = 0
    for f in sorted(subject_root.glob("*.osim")):
        _copy(f, opensim_dir / f.name, dry_run)
        count += 1
    for f in sorted(subject_root.glob("*scale_set*.xml")):
        _copy(f, opensim_dir / f.name, dry_run)
        count += 1
    if not count:
        print("  [warning] No .osim or scale_set .xml files found in subject root.")


# ---------------------------------------------------------------------------
# Trial session directories
# ---------------------------------------------------------------------------

def organise_trial_dir(
    trial_dir: Path,
    folder_type: str,
    output_type_dir: Path,
    subject_lower: str,
    dry_run: bool,
) -> None:
    """Copy/rename files from one source session folder into the output type folder."""
    for src in sorted(trial_dir.iterdir()):
        ext = src.suffix.lower()
        if ext in SKIP_EXTENSIONS:
            continue

        trial = extract_trial_name(src.stem, folder_type, subject_lower)
        if trial is None:
            print(f"  [skip] unrecognised name: {src.name}")
            continue

        if ext == ".trc":
            _copy(src, output_type_dir / "marker" / f"{trial}.trc", dry_run)

        elif ext == ".mot":
            if src.stem.endswith("_ik"):
                # Pre-computed IK result — place in ik/ (run_ik.py will overwrite)
                _copy(src, output_type_dir / "ik" / f"{trial}_ik.mot", dry_run)
            else:
                _copy(src, output_type_dir / "grf" / f"{trial}.mot", dry_run)

        elif ext == ".csv":
            _copy(src, output_type_dir / "mocap" / f"{trial}.csv", dry_run)

        elif ext == ".xml":
            pass  # GRF XMLs are regenerated by create_grf_xml.py

        else:
            print(f"  [skip] extension not handled: {src.name}")


# ---------------------------------------------------------------------------
# Main organise function
# ---------------------------------------------------------------------------

def organise(subject_root: Path, output_dir: Path, dry_run: bool) -> None:
    subject_lower = subject_root.name.lower()
    trial_dirs = discover_trial_dirs(subject_root)

    print(f"\n{'='*60}")
    print("opensim/")
    print('='*60)
    organise_opensim(subject_root, output_dir, dry_run)

    for folder_type, trial_dir in trial_dirs.items():
        output_name = FOLDER_TYPE_TO_OUTPUT[folder_type]
        output_type_dir = output_dir / output_name

        print(f"\n{'='*60}")
        print(f"{output_name}/  ←  {trial_dir.name}")
        print('='*60)

        if not dry_run:
            for sub in OUTPUT_SUBFOLDERS:
                (output_type_dir / sub).mkdir(parents=True, exist_ok=True)

        organise_trial_dir(trial_dir, folder_type, output_type_dir, subject_lower, dry_run)

    print(f"\nDone → {output_dir}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Organise cascade source files into the output folder structure."
    )
    p.add_argument("--subject-root", type=Path, default=DEFAULT_SOURCE,
                   help=f"Source directory. Default: {DEFAULT_SOURCE}")
    p.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT,
                   help=f"Output directory. Default: {DEFAULT_OUTPUT}")
    p.add_argument("--dry-run", action="store_true",
                   help="Print planned copies without doing anything.")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    organise(args.subject_root, args.output_dir, args.dry_run)


if __name__ == "__main__":
    main()
